import { Href } from "expo-router";
import { Timestamp } from "firebase/firestore";
import { Icon } from "phosphor-react-native";
import React, { ReactNode } from "react";
import {
  ActivityIndicator,
  ActivityIndicatorProps,
  ImageStyle,
  PressableProps,
  TextInput,
  TextInputProps,
  TextProps,
  TextStyle,
  TouchableOpacityProps,
  ViewStyle,
} from "react-native";

export type ScreenWrapperProps = {
  style?: ViewStyle;
  children: React.ReactNode;
};
export type ModalWrapperProps = {
  style?: ViewStyle;
  children: React.ReactNode;
  bg?: string;
  scrollEnabled: boolean;
  keyboardAvoiding: boolean;
};
export type accountOptionType = {
  title: string;
  icon: React.ReactNode;
  bgColor: string;
  routeName?: any;
  key: string;
};

export type TypoProps = {
  size?: number;
  color?: string;
  fontWeight?: TextStyle["fontWeight"];
  children: any | null;
  style?: TextStyle | any;
  textProps?: TextProps;
};

export type IconComponent = React.ComponentType<{
  height?: number;
  width?: number;
  strokeWidth?: number;
  color?: string;
  fill?: string;
}>;

export type IconProps = {
  name: string;
  color?: string;
  size?: number;
  strokeWidth?: number;
  fill?: string;
};

export type HeaderProps = {
  title?: string;
  style?: ViewStyle;
  leftIcon?: ReactNode;
  rightIcon?: ReactNode;
};

export type BackButtonProps = {
  style?: ViewStyle;
  iconSize?: number;
};
export type CategoryType = {
  label: string;
  value: string;
  icon: Icon;
  bgColor: string;
};
export type ExpenseCategoriesType = {
  [key: string]: CategoryType;
};
export type ProductsCategoryType = {
  label: string;
  value: string;
};
export type ProductsCategoriesType = {
  [key: string]: ProductsCategoryType;
};

export type SaleListType = {
  data: SellType[];
  title?: string;
  loading?: boolean;
  emptyListMessage?: string;
};

export type SaleItemProps = {
  item: SellType;
  index: number;
  handleClick: Function;
};

export interface InputProps extends TextInputProps {
  icon?: React.ReactNode;
  containerStyle?: ViewStyle;
  label: string;
  error: any;
  inputStyle?: TextStyle;
  inputRef?: React.RefObject<TextInput>;
  //   label?: string;
  //   error?: string;
}

export interface CustomButtonProps extends TouchableOpacityProps {
  style?: ViewStyle;
  onPress?: () => void;
  loading?: boolean;
  children: React.ReactNode;
}

export type ImageUploadProps = {
  file?: any;
  onSelect: (file: any) => void;
  onClear: () => void;
  containerStyle?: ViewStyle;
  imageStyle?: ViewStyle;
  placeholder?: string;
};

export type UserType = {
  uid?: string;
  email?: string | null;
  name: string | null;
  number: string | null;
  address: string | null;
  role?: "user" | "manager" | "admin";
  isEmployee?: true | false;
  image?: any;
} | null;

export type UserDataType = {
  name: string;
  number: string;
  address: string;
  image?: any;
};

export type AuthContextType = {
  user: UserType;
  setUser: Function;
  login: (
    email: string,
    password: string
  ) => Promise<{ success: boolean; msg?: string }>;
  register: (
    email: string,
    password: string,
    number: string,
    address: string,
    name: string
  ) => Promise<{ success: boolean; msg?: string }>;
  updateUserData: (userId: string) => Promise<void>;
};
export type BrandType = {
  id?: string; // Auto-generated by Firebase
  name: string; // نام برند (ضروری)
  businessName: string;
  category: string; // دسته‌بندی (تجهیزات پزشکی، آزمایشگاهی، ...)
  country: string; // کشور سازنده
  website?: string; // وبسایت رسمی
  description?: string; // توضیحات درباره برند
  logo?: string; // URL لوگوی برند
  createdAt: Date | string; // تاریخ ایجاد
  updatedAt: Date | string; // تاریخ آخرین ویرایش
  createdBy: string; // ID کاربر ایجادکننده
};
export type ResponseType = {
  success: boolean;
  data?: any;
  msg?: string;
};
export type InventoryType = {
  id?: string;
  name: string;
  category: string;
  brand?: string;
  purchasedPrice: number;
  sellingPrice: number;
  expireDate: Date | Timestamp | string;
  quantity?: number;
  description?: string;
  image?: any | null;
  created?: string;
  updated?: string;
  ownerName?: string;
};
export type ExpensesType = {
  id?: string;
  category: string;
  expenseCost: number;
  description?: string;
  image?: any | null;
  ownerName?: string;
  created?: Date | Timestamp | string;
};
export type AdminMSG = {
  id?: string;
  title: string;
  content: string;
  date: Date | string;
  sender: string;
};
export type AdminMessage = {
  title: string;
  message: string;
  priority?: "low" | "normal" | "high";
  created: Date;
  updatedAt: Date;
  expireDate: string;
  adminUserName: string;
  adminId?: string;
};
export type InventoryProduct = {
  id: string;
  name: string;
  quantity: number;
  sellingPrice: number;
};

export type SellType = {
  id?:string;
  inventoryProduct: string;
  quantity: number;
  Price: number;
  loan?: boolean;
  loanAmount?: number;
  PriceAfterLoan: number;
  discount?: number;
  date: Date | string | Timestamp;
  customerName?: string;
  customerNumber?: number;
  description?: string;
  ownerName?: string;
};
// export type ExpensesType1 = {
//   id?: string;
//   title: string;
//   expenseCostt: number;
//   category: string;
//   description?: string;
//   date: Date| Timestamp | string;
//   ownerName: string;
// };
